### ISSUE TITLE
Can't detect path to qemu-system-x86_64

### ISSUE THREAD

**Issue by tekenny** [stackhpc/ansible-role-libvirt-vm#22]
This might be a config problem on my hypervisor but haven't determined why qemu-system-x86_64 does not exist.

Attached are my simple playbook that fails and the output.

Any insights or suggestions on the cause are appreciated.

[makeVM.yml.txt](https://github.com/stackhpc/ansible-role-libvirt-vm/files/2769034/makeVM.yml.txt)

[makeVM.output.txt](https://github.com/stackhpc/ansible-role-libvirt-vm/files/2769038/makeVM.output.txt)

**Comment by tekenny** [comment]
I should have mentioned that this is on an x86_64 RHEL 7.6 system and I used the attached playbook using your stackhpc.libvirt-host role. Thanks for these roles btw. I was creating an x86_64 VM.

I tried to work around the issue by adding "ignore_errors: yes" in autodetect.yml (after line 52) and it did  proceed further but failed at the "Ensure the VM is defined" task stating "XML error: No PCI buses available"

Sorry but I don't know kvm/qemu that well so I don't know what may be missing or mis-configured. 

[kvm.yml.txt](https://github.com/stackhpc/ansible-role-libvirt-vm/files/2771123/kvm.yml.txt)

**Comment by tekenny** [comment]
I reinstalled the role and used libvirt_vm_engine: kvm as well as not set it and this issue did not exist. So this issue was due to me specifying the wrong engine. Sorry about that and thanks for pointing it out and for the great kvm roles!

I still have a No PCI buses issue but I see that the virsh create is failing and the XML generated look fine to me.

Thanks again for your help!

**Comment by markgoddard** [comment]
Great, glad to hear it helped.
