### ISSUE TITLE
XML_template should be XML_file in README

### ISSUE THREAD

**Issue by tgupta3** [stackhpc/ansible-role-libvirt-vm#26]
Hi, 

The README mentions that the custom xml template can be specified by using xml_template as variable. However in defaults/main.yml, the template is being defined by xml_file, so it should be accessible using vm.xml_file for a particular vm which is what it's defined in tasks/vm.xml

Thanks

**Comment by markgoddard** [comment]
Thanks for raising this. Now fixed.
