### ISSUE TITLE
Support for network disks

### ISSUE THREAD

**Issue by goetzk** [stackhpc/ansible-role-libvirt-vm#35]
Hi,
I've been trying to massage in support for network filesystems - like ceph - as backing stock for instances.

https://github.com/goetzk/ansible-role-libvirt-vm/commit/69364760c7166757f2b87850d584049e0d2755f5

The problem I'm having with a minimal change addition is that the volume creation calls virt-volume.sh to do the volume creation - a step which isn't needed on a network disk.

Do you have a preferred way of circumventing this problem?
Karl.

**Comment by markgoddard** [comment]
Hi Karl, I left a comment on your commit.

**Comment by markgoddard** [comment]
It will also need to skip that script when state=absent.
