### ISSUE TITLE
howto pass "extra-args" to a VM

### ISSUE THREAD

**Issue by harenber** [stackhpc/ansible-role-libvirt-vm#54]
Sorry for opening an "issue", it's more a question (I searched for quite a while but couldn't figure it out):

is there any way to create a VM with this role and pass "extra-args" for kickstart to it? Like you do a
 
`virt-install -x "ks=URL ksdevice=eth0 ip=IP netmask=IP dns=IP gateway=IP"`

Thanks for any answer!

 Torsten

**Comment by jovial** [comment]
I don't think this is possible at the moment as the role would have to support something like [direct kernel boot](https://libvirt.org/formatdomain.html). Can you use a generic cloud image instead? Here are some generic cloud images:
- https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
- https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64.qcow2

**Comment by harenber** [comment]
Thanks for the quick reply!!!  Yes, I do nothing fancy with Kickstart, so definetely cloud images would work for me as well.
