### ISSUE TITLE
Network interface driver should be tunable

### ISSUE THREAD

**Issue by gprocunier** [stackhpc/ansible-role-libvirt-vm#65]
There are reasonable reasons to not use virtio as the default network driver for network interfaces.

Eg.
Windows Guests (native boot)
Linux guests being used in a network simulator which need mii-mon (e1000 supports it).

Modifying this seems trivial : 

https://github.com/stackhpc/ansible-role-libvirt-vm/blob/master/templates/vm.xml.j2#L82

to be 

```
{% if interface.driver is defined %}
      <model type='{{ interface.driver }}/>'
{% else %}
      <model type='virtio'/>
{% endif %}
```

**Comment by markgoddard** [comment]
@gprocunier feel free to propose a PR for this.

**Comment by gprocunier** [comment]
Done
