### ISSUE TITLE
Changing definition of VM does not seem to update VM

### ISSUE THREAD

**Issue by thomwiggers** [stackhpc/ansible-role-libvirt-vm#74]
I've changed the definition of my vm, eg. the amount of RAM, but the "ensure the VM is defined" task doesn't do anything.

I'm running Debian 10 with KVM. `libvirt-python` is version 5.0. I've checked using ``virsh define updated.xml``. ``updated.xml`` was created via ``virsh dumpxml > updated.xml`` and then changing the number of CPU cores. If I then do ``virsh dumpxml --inactive | grep vcpu`` I see the new value.

But if I try to make the same change via this Ansible module, nothing happens.

**Comment by thomwiggers** [comment]
though that might just be https://github.com/ansible-collections/community.libvirt/pull/48

**Comment by thomwiggers** [comment]
It's a problem in the `community.virt.libvirt` command.

**Comment by thomwiggers** [comment]
https://github.com/ansible-collections/community.libvirt/issues/53

**Comment by markgoddard** [comment]
Thanks for updating.
