### ISSUE TITLE
The error was: no test named 'eq'

### ISSUE THREAD

**Issue by Xachman** [stackhpc/ansible-role-libvirt-vm#8]
I got the error 

The error was: no test named 'eq'

when using this role.

https://github.com/stackhpc/ansible-role-libvirt-vm/blob/master/tasks/main.yml#L7

it was related to this line.

I changed this eq to equalto and it worked.  Not sure if this is an appropriate fix so  I made this issue.

**Comment by markgoddard** [comment]
Which version of ansible and Jinja are you using?

**Comment by markgoddard** [comment]
I have fixed this here: https://github.com/stackhpc/ansible-role-libvirt-vm/commit/3975c10b097a29ea85cf2168287f6fd3cd7744e

**Comment by Xachman** [comment]
Thanks!
