### ISSUE TITLE
Using libvirt modules

### ISSUE THREAD

**Issue by damfle** [stackhpc/ansible-role-libvirt-vm#85]
More a question than an issue. Why aren't you using only libvirt's modules (especially volumes) ?
My first role, before migrating to this one, was only using it and did not require all that bash glue.
It would make the entire thing more standard and easier to maintain.

**Comment by markgoddard** [comment]
I don't see a module for managing volumes.

**Comment by markgoddard** [comment]
https://galaxy.ansible.com/community/libvirt?extIdCarryOver=true&sc_cid=701f2000001OH7YAAW

**Comment by damfle** [comment]
Yes you're right.. Nevermind... Sorry for the noise
